### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ArsalaMehr** [BushraSheeraz/task-may-14#3]
To make website responsive use flex in parent section and use further properties accordingly
https://github.com/BushraSheeraz/task-may-14/blob/a9e98bf4815f8e398ace29ceabaaebcc801114c7/style.css#L39

**Comment by Chensokheng** [comment]
Hello, I would love working on this issue. Can you let me help you with issue?

**Comment by BushraSheeraz** [comment]
#3 solve
